version: "3.9"

services:
  fastapi:
    container_name: backend_app
    build: .
    command: uvicorn src.backend.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge
